const shred_g_cascade_pentatonic_major = {
  bpm: 180,
  tuning: "standard_6",
  key: 11,
  scale: "pentatonic_major",
  feel: "cascade",
  figure: [
    { string: 6, fret: 15, finger: 4 },
    { string: 6, fret: 12, finger: 1 },
    { string: 6, fret: 15, finger: 4 },
    { string: 5, fret: 12, finger: 1 },
    { string: 6, fret: 15, finger: 4 },
    { string: 5, fret: 12, finger: 1 },
    { string: 5, fret: 14, finger: 3 },
    { string: 5, fret: 12, finger: 1 },
    { string: 5, fret: 14, finger: 3 },
    { string: 4, fret: 12, finger: 1 },
    { string: 5, fret: 14, finger: 3 },
    { string: 4, fret: 12, finger: 1 },
    { string: 4, fret: 14, finger: 3 },
    { string: 4, fret: 12, finger: 1 },
    { string: 4, fret: 14, finger: 3 },
    { string: 3, fret: 12, finger: 1 },
    { string: 4, fret: 14, finger: 3 },
    { string: 3, fret: 12, finger: 1 },
    { string: 3, fret: 14, finger: 3 },
    { string: 3, fret: 12, finger: 1 },
    { string: 3, fret: 14, finger: 3 },
    { string: 2, fret: 12, finger: 1 },
    { string: 3, fret: 14, finger: 3 },
    { string: 2, fret: 12, finger: 1 },
    { string: 2, fret: 15, finger: 4 },
    { string: 2, fret: 12, finger: 1 },
    { string: 2, fret: 15, finger: 4 },
    { string: 1, fret: 12, finger: 1 },
    { string: 2, fret: 15, finger: 4 },
    { string: 1, fret: 12, finger: 1 },
    { string: 1, fret: 15, finger: 4 },
    { string: 1, fret: 12, finger: 1 },
    { string: 2, fret: 15, finger: 4 },
    { string: 1, fret: 12, finger: 1 },
    { string: 2, fret: 15, finger: 4 },
    { string: 2, fret: 12, finger: 1 },
    { string: 3, fret: 14, finger: 4 },
    { string: 2, fret: 12, finger: 1 },
    { string: 3, fret: 14, finger: 4 },
    { string: 3, fret: 12, finger: 1 },
    { string: 4, fret: 14, finger: 4 },
    { string: 3, fret: 12, finger: 1 },
    { string: 4, fret: 14, finger: 3 },
    { string: 4, fret: 12, finger: 1 },
    { string: 4, fret: 14, finger: 3 },
  ],
};

export default shred_g_cascade_pentatonic_major;
