const shred_b_neoclassical_minor = {
  bpm: 180,
  tunning: "standard_6",
  key: 3, // B
  scale: "harmonic_minor",
  feel: "neoclassical",
  figure: [
    { string: 6, fret: 7, finger: 1 },
    { string: 6, fret: 10, finger: 4 },
    { string: 5, fret: 9, finger: 1 },
    { string: 4, fret: 9, finger: 1 },
    { string: 4, fret: 12, finger: 4 },
    { string: 5, fret: 9, finger: 1 },
    { string: 5, fret: 14, finger: 4 },
    { string: 4, fret: 12, finger: 2 },
    { string: 3, fret: 11, finger: 1 },
    { string: 3, fret: 16, finger: 4 },
    { string: 4, fret: 12, finger: 1 },
    { string: 4, fret: 16, finger: 4 },
    { string: 3, fret: 16, finger: 4 },
    { string: 2, fret: 15, finger: 1 },
    { string: 2, fret: 19, finger: 4 },
    { string: 3, fret: 16, finger: 1 },
    { string: 3, fret: 19, finger: 1 },
    { string: 2, fret: 19, finger: 1 },
    { string: 1, fret: 19, finger: 1 },
    { string: 1, fret: 22, finger: 4 },
    { string: 1, fret: 21, finger: 4 },
    { string: 1, fret: 18, finger: 1 },
    { string: 2, fret: 19, finger: 2 },
    { string: 3, fret: 21, finger: 4 },
    { string: 3, fret: 18, finger: 1 },
    { string: 2, fret: 19, finger: 4 },
    { string: 2, fret: 17, finger: 1 },
    { string: 3, fret: 18, finger: 2 },
    { string: 4, fret: 20, finger: 4 },
    { string: 4, fret: 16, finger: 1 },
    { string: 3, fret: 18, finger: 4 },
    { string: 3, fret: 15, finger: 1 },
    { string: 4, fret: 16, finger: 2 },
    { string: 5, fret: 19, finger: 4 },
    { string: 5, fret: 16, finger: 1 },
    { string: 4, fret: 16, finger: 3 },
    { string: 4, fret: 14, finger: 1 },
    { string: 5, fret: 16, finger: 2 },
    { string: 6, fret: 18, finger: 4 },
    { string: 6, fret: 14, finger: 1 },
    { string: 6, fret: 15, finger: 1 },
    { string: 6, fret: 19, finger: 4 },
    { string: 5, fret: 17, finger: 2 },
    { string: 4, fret: 16, finger: 1 },
    { string: 4, fret: 17, finger: 2 },
    { string: 5, fret: 14, finger: 1 },
    { string: 5, fret: 17, finger: 4 },
    { string: 4, fret: 16, finger: 2 },
    { string: 3, fret: 12, finger: 1 },
    { string: 3, fret: 16, finger: 4 },
    { string: 4, fret: 12, finger: 1 },
    { string: 4, fret: 16, finger: 4 },
    { string: 3, fret: 12, finger: 1 },
    { string: 2, fret: 12, finger: 1 },
    { string: 2, fret: 15, finger: 4 },
    { string: 4, fret: 12, finger: 3 },
    { string: 3, fret: 12, finger: 3 },
    { string: 2, fret: 12, finger: 3 },
    { string: 1, fret: 10, finger: 1 },
    { string: 1, fret: 14, finger: 4 },
    { string: 1, fret: 12, finger: 4 },
    { string: 1, fret: 9, finger: 1 },
    { string: 2, fret: 11, finger: 2 },
    { string: 3, fret: 12, finger: 4 },
    { string: 3, fret: 9, finger: 1 },
    { string: 2, fret: 11, finger: 4 },
    { string: 2, fret: 8, finger: 1 },
    { string: 3, fret: 9, finger: 2 },
    { string: 4, fret: 11, finger: 4 },
    { string: 4, fret: 8, finger: 1 },
    { string: 3, fret: 9, finger: 4 },
    { string: 3, fret: 6, finger: 1 },
    { string: 4, fret: 8, finger: 2 },
    { string: 5, fret: 10, finger: 4 },
    { string: 5, fret: 7, finger: 1 },
    { string: 4, fret: 8, finger: 4 },
    { string: 4, fret: 5, finger: 1 },
    { string: 5, fret: 7, finger: 2 },
    { string: 6, fret: 9, finger: 4 },
    { string: 6, fret: 6, finger: 1 },
  ],
};

export default shred_b_neoclassical_minor;
