const shred_c_runner_halfwhole_diminished = {
  bpm: 180,
  tuning: "standard_6",
  key: 4,
  scale: "half_whole_diminished",
  feel: "dimished",
  figure: [
    { string: 6, fret: 8, finger: 1 }, 
    { string: 6, fret: 9, finger: 2 }, 
    { string: 6, fret: 11, finger: 4 },
    { string: 5, fret: 9, finger: 1 },
    { string: 5, fret: 10, finger: 2 },
    { string: 5, fret: 12, finger: 4 },
    { string: 5, fret: 10, finger: 1 },
    { string: 5, fret: 12, finger: 2 },
    { string: 5, fret: 13, finger: 4 },
    { string: 4, fret: 10, finger: 1 },
    { string: 4, fret: 11, finger: 2 },
    { string: 4, fret: 13, finger: 4 },
    { string: 4, fret: 11, finger: 1 },
    { string: 4, fret: 13, finger: 2 },
    { string: 4, fret: 14, finger: 4 },
    { string: 3, fret: 11, finger: 1 },
    { string: 3, fret: 12, finger: 2 },
    { string: 3, fret: 14, finger: 4 },
    { string: 3, fret: 12, finger: 1 },
    { string: 3, fret: 14, finger: 2 },
    { string: 3, fret: 15, finger: 4 },
    { string: 2, fret: 13, finger: 1 },
    { string: 2, fret: 14, finger: 2 },
    { string: 2, fret: 16, finger: 4 },
    { string: 2, fret: 14, finger: 1 },
    { string: 2, fret: 16, finger: 2 },
    { string: 2, fret: 17, finger: 4 },
    { string: 1, fret: 14, finger: 1 },
    { string: 1, fret: 15, finger: 2 },
    { string: 1, fret: 17, finger: 4 },
  ],
};

export default shred_c_runner_halfwhole_diminished;