const shred_c_modern_runner_outside = {
  bpm: 180,
  tunning: "standard_6",
  key: 4,
  scale: "harmonic_minor_outside",
  feel: "modern / outside",
  figure: [
    { string: 6, fret: 8, finger: 1 },
    { string: 6, fret: 11, finger: 2 },
    { string: 6, fret: 13, finger: 4 },
    { string: 5, fret: 9, finger: 1 },
    { string: 5, fret: 10, finger: 2 },
    { string: 5, fret: 13, finger: 4 },
    { string: 5, fret: 10, finger: 2 },
    { string: 5, fret: 9, finger: 1 },
    { string: 5, fret: 10, finger: 1 },
    { string: 5, fret: 13, finger: 2 },
    { string: 5, fret: 15, finger: 4 },
    { string: 3, fret: 11, finger: 1 },
    { string: 3, fret: 12, finger: 2 },
    { string: 3, fret: 15, finger: 4 },
    { string: 3, fret: 12, finger: 2 },
    { string: 3, fret: 11, finger: 1 },
    { string: 3, fret: 12, finger: 1 },
    { string: 3, fret: 15, finger: 2 },
    { string: 3, fret: 17, finger: 4 },
    { string: 1, fret: 14, finger: 1 },
    { string: 1, fret: 15, finger: 2 },
    { string: 1, fret: 18, finger: 4 },
    { string: 1, fret: 15, finger: 2 },
    { string: 1, fret: 14, finger: 1 },
    { string: 1, fret: 15, finger: 1 },
    { string: 1, fret: 18, finger: 2 },
    { string: 1, fret: 20, finger: 4 },
    { string: 1, fret: 18, finger: 2 },
    { string: 1, fret: 15, finger: 1 },
    { string: 2, fret: 20, finger: 4 },
    { string: 2, fret: 17, finger: 2 },
    { string: 2, fret: 15, finger: 1 },
    { string: 2, fret: 17, finger: 2 },
  ],
};

export default shred_c_modern_runner_outside;
