const FIFTHS = [
  {
    id: 1,
    name: 'A',
    context: [
      { id: 1, name: 'A' },
      { id: 2, name: 'Bm' },
      { id: 3, name: 'C#m' },
      { id: 4, name: 'D' },
      { id: 5, name: 'E' },
      { id: 6, name: 'F#m' },
      { id: 7, name: 'G#dim' },
    ],
  },
  {
    id: 2,
    name: 'A#',
    context: [
      { id: 1, name: 'A#' },
      { id: 2, name: 'Cm' },
      { id: 3, name: 'Dm' },
      { id: 4, name: 'D#' },
      { id: 5, name: 'F' },
      { id: 6, name: 'Gm' },
      { id: 7, name: 'Adim' },
    ],
  },
  {
    id: 3,
    name: 'B',
    context: [
      { id: 1, name: 'B' },
      { id: 2, name: 'C#m' },
      { id: 3, name: 'D#m' },
      { id: 4, name: 'E' },
      { id: 5, name: 'F#' },
      { id: 6, name: 'G#m' },
      { id: 7, name: 'Adim' },
    ],
  },
  {
    id: 4,
    name: 'C',
    context: [
      { id: 1, name: 'C' },
      { id: 2, name: 'Dm' },
      { id: 3, name: 'Em' },
      { id: 4, name: 'F' },
      { id: 5, name: 'G' },
      { id: 6, name: 'Am' },
      { id: 7, name: 'Bdim' },
    ],
  },
  {
    id: 5,
    name: 'C#',
    context: [
      { id: 1, name: 'C#' },
      { id: 2, name: 'D#m' },
      { id: 3, name: 'Fm' },
      { id: 4, name: 'F#' },
      { id: 5, name: 'G#' },
      { id: 6, name: 'A#m' },
      { id: 7, name: 'Cdim' },
    ],
  },
  {
    id: 6,
    name: 'D',
    context: [
      { id: 1, name: 'D' },
      { id: 2, name: 'Em' },
      { id: 3, name: 'F#m' },
      { id: 4, name: 'G' },
      { id: 5, name: 'A' },
      { id: 6, name: 'Bm' },
      { id: 7, name: 'C#dim' },
    ],
  },
  {
    id: 7,
    name: 'D#',
    context: [
      { id: 1, name: 'D#' },
      { id: 2, name: 'Fm' },
      { id: 3, name: 'Gm' },
      { id: 4, name: 'G#' },
      { id: 5, name: 'A#' },
      { id: 6, name: 'Cm' },
      { id: 7, name: 'Ddim' },
    ],
  },
  {
    id: 8,
    name: 'E',
    context: [
      { id: 1, name: 'E' },
      { id: 2, name: 'F#m' },
      { id: 3, name: 'G#m' },
      { id: 4, name: 'A' },
      { id: 5, name: 'B' },
      { id: 6, name: 'C#m' },
      { id: 7, name: 'D#dim' },
    ],
  },
  {
    id: 9,
    name: 'F',
    context: [
      { id: 1, name: 'F' },
      { id: 2, name: 'Gm' },
      { id: 3, name: 'Am' },
      { id: 4, name: 'A#' },
      { id: 5, name: 'C' },
      { id: 6, name: 'Dm' },
      { id: 7, name: 'Edim' },
    ],
  },
  {
    id: 10,
    name: 'F#',
    context: [
      { id: 1, name: 'F#' },
      { id: 2, name: 'G#m' },
      { id: 3, name: 'A#m' },
      { id: 4, name: 'B' },
      { id: 5, name: 'C#' },
      { id: 6, name: 'D#m' },
      { id: 7, name: 'Fdim' },
    ],
  },
  {
    id: 11,
    name: 'G',
    context: [
      { id: 1, name: 'G' },
      { id: 2, name: 'Am' },
      { id: 3, name: 'Bm' },
      { id: 4, name: 'C' },
      { id: 5, name: 'D' },
      { id: 6, name: 'Em' },
      { id: 7, name: 'F#dim' },
    ],
  },
  {
    id: 12,
    name: 'G#',
    context: [
      { id: 1, name: 'G#' },
      { id: 2, name: 'A#m' },
      { id: 3, name: 'Cm' },
      { id: 4, name: 'C#' },
      { id: 5, name: 'D#' },
      { id: 6, name: 'Fm' },
      { id: 7, name: 'Gdim' },
    ],
  },
];

export default FIFTHS;
