const little_finger_strength = {
  bpm: 120,
  tunning: null,
  key: null,
  scale: null,
  feel: null,
  figure: [
    { string: 6, fret: 2, finger: 3 },
    { string: 6, fret: 3, finger: 4 },
    { string: 5, fret: 2, finger: 3 },
    { string: 5, fret: 3, finger: 4 },
    { string: 4, fret: 2, finger: 3 },
    { string: 4, fret: 3, finger: 4 },
    { string: 3, fret: 2, finger: 3 },
    { string: 3, fret: 3, finger: 4 },
    { string: 2, fret: 2, finger: 3 },
    { string: 2, fret: 3, finger: 4 },
    { string: 1, fret: 2, finger: 3 },
    { string: 1, fret: 3, finger: 4 },
    { string: 1, fret: 4, finger: 4 },
    { string: 1, fret: 3, finger: 3 },
    { string: 2, fret: 4, finger: 4 },
    { string: 2, fret: 3, finger: 3 },
    { string: 3, fret: 4, finger: 4 },
    { string: 3, fret: 3, finger: 3 },
    { string: 4, fret: 4, finger: 4 },
    { string: 4, fret: 3, finger: 3 },
    { string: 5, fret: 4, finger: 4 },
    { string: 5, fret: 3, finger: 3 },
    { string: 6, fret: 4, finger: 4 },
    { string: 6, fret: 3, finger: 3 },
    { string: 6, fret: 4, finger: 3 },
    { string: 6, fret: 5, finger: 4 },
    { string: 5, fret: 4, finger: 3 },
    { string: 5, fret: 5, finger: 4 },
    { string: 4, fret: 4, finger: 3 },
    { string: 4, fret: 5, finger: 4 },
    { string: 3, fret: 4, finger: 3 },
    { string: 3, fret: 5, finger: 4 },
    { string: 2, fret: 4, finger: 3 },
    { string: 2, fret: 5, finger: 4 },
    { string: 1, fret: 4, finger: 3 },
    { string: 1, fret: 5, finger: 4 },
    { string: 1, fret: 6, finger: 4 },
    { string: 1, fret: 5, finger: 3 },
    { string: 2, fret: 6, finger: 3 },
    { string: 2, fret: 5, finger: 4 },
    { string: 3, fret: 6, finger: 3 },
    { string: 3, fret: 5, finger: 4 },
    { string: 4, fret: 6, finger: 3 },
    { string: 4, fret: 5, finger: 4 },
    { string: 5, fret: 6, finger: 3 },
    { string: 5, fret: 5, finger: 4 },
    { string: 6, fret: 6, finger: 3 },
    { string: 6, fret: 5, finger: 4 },
  ],
};

export default little_finger_strength;
