const little_finger_strength = {
  bpm: 120,
  figure: [
    { string: 6, fret: 2 },
    { string: 6, fret: 3 },
    { string: 5, fret: 2 },
    { string: 5, fret: 3 },
    { string: 4, fret: 2 },
    { string: 4, fret: 3 },
    { string: 3, fret: 2 },
    { string: 3, fret: 3 },
    { string: 2, fret: 2 },
    { string: 2, fret: 3 },
    { string: 1, fret: 2 },
    { string: 1, fret: 3 },
    { string: 1, fret: 4 },
    { string: 1, fret: 3 },
    { string: 2, fret: 4 },
    { string: 2, fret: 3 },
    { string: 3, fret: 4 },
    { string: 3, fret: 3 },
    { string: 4, fret: 4 },
    { string: 4, fret: 3 },
    { string: 5, fret: 4 },
    { string: 5, fret: 3 },
    { string: 6, fret: 4 },
    { string: 6, fret: 3 },
    { string: 6, fret: 4 },
    { string: 6, fret: 5 },
    { string: 5, fret: 4 },
    { string: 5, fret: 5 },
    { string: 4, fret: 4 },
    { string: 4, fret: 5 },
    { string: 3, fret: 4 },
    { string: 3, fret: 5 },
    { string: 2, fret: 4 },
    { string: 2, fret: 5 },
    { string: 1, fret: 4 },
    { string: 1, fret: 5 },
    { string: 1, fret: 6 },
    { string: 1, fret: 5 },
    { string: 2, fret: 6 },
    { string: 2, fret: 5 },
    { string: 3, fret: 6 },
    { string: 3, fret: 5 },
    { string: 4, fret: 6 },
    { string: 4, fret: 5 },
    { string: 5, fret: 6 },
    { string: 5, fret: 5 },
    { string: 6, fret: 6 },
    { string: 6, fret: 5 },
  ],
  repeat_inverse: false,
};

export default little_finger_strength;
