const spider = {
  bpm: 120,
  repeat_inverse: true,
  figure: [
    { string: 6, fret: 1, finger: 1 },
    { string: 6, fret: 2, finger: 2 },
    { string: 6, fret: 3, finger: 3 },
    { string: 6, fret: 4, finger: 4 },
    { string: 5, fret: 1, finger: 1 },
    { string: 5, fret: 2, finger: 2 },
    { string: 5, fret: 3, finger: 3 },
    { string: 5, fret: 4, finger: 4 },
    { string: 4, fret: 1, finger: 1 },
    { string: 4, fret: 2, finger: 2 },
    { string: 4, fret: 3, finger: 3 },
    { string: 4, fret: 4, finger: 4 },
    { string: 3, fret: 1, finger: 1 },
    { string: 3, fret: 2, finger: 2 },
    { string: 3, fret: 3, finger: 3 },
    { string: 3, fret: 4, finger: 4 },
    { string: 2, fret: 1, finger: 1 },
    { string: 2, fret: 2, finger: 2 },
    { string: 2, fret: 3, finger: 3 },
    { string: 2, fret: 4, finger: 4 },
    { string: 1, fret: 1, finger: 1 },
    { string: 1, fret: 2, finger: 2 },
    { string: 1, fret: 3, finger: 3 },
    { string: 1, fret: 4, finger: 4 },
  ],
};

export default spider;
