const spider = {
  bpm: 120,
  figure: [
    { string: 6, fret: 1 },
    { string: 6, fret: 2 },
    { string: 6, fret: 3 },
    { string: 6, fret: 4 },
    { string: 5, fret: 1 },
    { string: 5, fret: 2 },
    { string: 5, fret: 3 },
    { string: 5, fret: 4 },
    { string: 4, fret: 1 },
    { string: 4, fret: 2 },
    { string: 4, fret: 3 },
    { string: 4, fret: 4 },
    { string: 3, fret: 1 },
    { string: 3, fret: 2 },
    { string: 3, fret: 3 },
    { string: 3, fret: 4 },
    { string: 2, fret: 1 },
    { string: 2, fret: 2 },
    { string: 2, fret: 3 },
    { string: 2, fret: 4 },
    { string: 1, fret: 1 },
    { string: 1, fret: 2 },
    { string: 1, fret: 3 },
    { string: 1, fret: 4 },
  ],
  repeat_inverse: true,
};

export default spider;
