const NOTES_EXTENDED_FOR_MIDI = [
    // Octave 0
    { id: 1, name: 'A', octave: 0, midiId: 21 },
    { id: 2, name: 'A#', octave: 0, midiId: 22 },
    { id: 3, name: 'B', octave: 0, midiId: 23 },
    // Octave 1
    { id: 4, name: 'C', octave: 1, midiId: 24 },
    { id: 5, name: 'C#', octave: 1, midiId: 25 },
    { id: 6, name: 'D', octave: 1, midiId: 26 },
    { id: 7, name: 'D#', octave: 1, midiId: 27 },
    { id: 8, name: 'E', octave: 1, midiId: 28 },
    { id: 9, name: 'F', octave: 1, midiId: 29 },
    { id: 10, name: 'F#', octave: 1, midiId: 30 },
    { id: 11, name: 'G', octave: 1, midiId: 31 },
    { id: 12, name: 'G#', octave: 1, midiId: 32 },
    { id: 13, name: 'A', octave: 1, midiId: 33 },
    { id: 14, name: 'A#', octave: 1, midiId: 34 },
    { id: 15, name: 'B', octave: 1, midiId: 35 },
    // Octave 2
    { id: 16, name: 'C', octave: 2, midiId: 36 },
    { id: 17, name: 'C#', octave: 2, midiId: 37 },
    { id: 18, name: 'D', octave: 2, midiId: 38 },
    { id: 19, name: 'D#', octave: 2, midiId: 39 },
    { id: 20, name: 'E', octave: 2, midiId: 40 },
    { id: 21, name: 'F', octave: 2, midiId: 41 },
    { id: 22, name: 'F#', octave: 2, midiId: 42 },
    { id: 23, name: 'G', octave: 2, midiId: 43 },
    { id: 24, name: 'G#', octave: 2, midiId: 44 },
    { id: 25, name: 'A', octave: 2, midiId: 45 },
    { id: 26, name: 'A#', octave: 2, midiId: 46 },
    { id: 27, name: 'B', octave: 2, midiId: 47 },
    // Octave 3
    { id: 28, name: 'C', octave: 3, midiId: 48 },
    { id: 29, name: 'C#', octave: 3, midiId: 49 },
    { id: 30, name: 'D', octave: 3, midiId: 50 },
    { id: 31, name: 'D#', octave: 3, midiId: 51 },
    { id: 32, name: 'E', octave: 3, midiId: 52 },
    { id: 33, name: 'F', octave: 3, midiId: 53 },
    { id: 34, name: 'F#', octave: 3, midiId: 54 },
    { id: 35, name: 'G', octave: 3, midiId: 55 },
    { id: 36, name: 'G#', octave: 3, midiId: 56 },
    { id: 37, name: 'A', octave: 3, midiId: 57 },
    { id: 38, name: 'A#', octave: 3, midiId: 58 },
    { id: 39, name: 'B', octave: 3, midiId: 59 },
    // Octave 4
    { id: 40, name: 'C', octave: 4, midiId: 60 },
    { id: 41, name: 'C#', octave: 4, midiId: 61 },
    { id: 42, name: 'D', octave: 4, midiId: 62 },
    { id: 43, name: 'D#', octave: 4, midiId: 63 },
    { id: 44, name: 'E', octave: 4, midiId: 64 },
    { id: 45, name: 'F', octave: 4, midiId: 65 },
    { id: 46, name: 'F#', octave: 4, midiId: 66 },
    { id: 47, name: 'G', octave: 4, midiId: 67 },
    { id: 48, name: 'G#', octave: 4, midiId: 68 },
    { id: 49, name: 'A', octave: 4, midiId: 69 },
    { id: 50, name: 'A#', octave: 4, midiId: 70 },
    { id: 51, name: 'B', octave: 4, midiId: 71 },
    // Octave 5
    { id: 52, name: 'C', octave: 5, midiId: 72 },
    { id: 53, name: 'C#', octave: 5, midiId: 73 },
    { id: 54, name: 'D', octave: 5, midiId: 74 },
    { id: 55, name: 'D#', octave: 5, midiId: 75 },
    { id: 56, name: 'E', octave: 5, midiId: 76 },
    { id: 57, name: 'F', octave: 5, midiId: 77 },
    { id: 58, name: 'F#', octave: 5, midiId: 78 },
    { id: 59, name: 'G', octave: 5, midiId: 79 },
    { id: 60, name: 'G#', octave: 5, midiId: 80 },
    { id: 61, name: 'A', octave: 5, midiId: 81 },
    { id: 62, name: 'A#', octave: 5, midiId: 82 },
    { id: 63, name: 'B', octave: 5, midiId: 83 },
    // Octave 6
    { id: 64, name: 'C', octave: 6, midiId: 84 },
    { id: 65, name: 'C#', octave: 6, midiId: 85 },
    { id: 66, name: 'D', octave: 6, midiId: 86 },
    { id: 67, name: 'D#', octave: 6, midiId: 87 },
    { id: 68, name: 'E', octave: 6, midiId: 88 },
    { id: 69, name: 'F', octave: 6, midiId: 89 },
    { id: 70, name: 'F#', octave: 6, midiId: 90 },
    { id: 71, name: 'G', octave: 6, midiId: 91 },
    { id: 72, name: 'G#', octave: 6, midiId: 92 },
    { id: 73, name: 'A', octave: 6, midiId: 93 },
    { id: 74, name: 'A#', octave: 6, midiId: 94 },
    { id: 75, name: 'B', octave: 6, midiId: 95 },
    // Octave 7
    { id: 76, name: 'C', octave: 7, midiId: 96 },
    { id: 77, name: 'C#', octave: 7, midiId: 97 },
    { id: 78, name: 'D', octave: 7, midiId: 98 },
    { id: 79, name: 'D#', octave: 7, midiId: 99 },
    { id: 80, name: 'E', octave: 7, midiId: 100 },
    { id: 81, name: 'F', octave: 7, midiId: 101 },
    { id: 82, name: 'F#', octave: 7, midiId: 102 },
    { id: 83, name: 'G', octave: 7, midiId: 103 },
    { id: 84, name: 'G#', octave: 7, midiId: 104 },
    { id: 85, name: 'A', octave: 7, midiId: 105 },
    { id: 86, name: 'A#', octave: 7, midiId: 106 },
    { id: 87, name: 'B', octave: 7, midiId: 107 },
    // Octave 8
    { id: 88, name: 'C', octave: 8, midiId: 108 },
    { id: 89, name: 'C#', octave: 8, midiId: 109 },
    { id: 90, name: 'D', octave: 8, midiId: 110 },
    { id: 91, name: 'D#', octave: 8, midiId: 111 },
    { id: 92, name: 'E', octave: 8, midiId: 112 },
    { id: 93, name: 'F', octave: 8, midiId: 113 },
    { id: 94, name: 'F#', octave: 8, midiId: 114 },
    { id: 95, name: 'G', octave: 8, midiId: 115 },
    { id: 96, name: 'G#', octave: 8, midiId: 116 },
  ];
  
  export default NOTES_EXTENDED_FOR_MIDI;
